### ISSUE TITLE
`p` in `a` leads to broken link when converting to markdown

### ISSUE THREAD

**Issue by martinratinaud** [OpenTermsArchive/engine#917] opened 2022-08-30 13:18 UTC
This might be the expected behavior and to be handle with a specific filter but I believe it's not

Example:

```
<ul>
<li><a href="#SCItemConditions2"><p>ARTICLE I. OBJET</p></a></li>
</ul>
```

leads to 
```
[

ARTICLE I. OBJET

](#SCItemConditions2)
```

Here is [an example](https://contribute.opentermsarchive.org/en/service?destination=OpenTermsArchive%2Fp2b-compliance-declarations&documentType=Marketplace%20Sellers%20Conditions&executeClientScripts=true&expertMode=true&name=Galeries%20Lafayette&selectedCss[]=.mainContent&url=https%3A%2F%2Fwww.galerieslafayette.com%2Fservice%2Fconditions-generals) on the contribution tool (Click on `Verify Version`)

**Comment by Ndpnt** [comment] 2022-08-31 10:06
Fixed in this PR https://github.com/mixmark-io/turndown/pull/419

**Comment by martinratinaud** [comment] 2022-09-06 05:21
@Ndpnt this has been 6 days so I think we should proceed with our own fork.
Last commit was done 10 months ago

**Comment by martinratinaud** [comment] 2022-09-06 14:17
@Ndpnt where is the PR where you use this fork? I did not see it

**Comment by MattiSG** [comment] 2023-04-24 09:58
Duplicate of #903.

**Closed by MattiSG** 2023-04-24 09:58 UTC
